- name: "Update apt"
  become: true
  shell: |
    apt-get update -y

- name: "Install Python package"
  become: true
  shell: |
    apt-get install python3.6 -y

- name: "Install NodeJS package"
  become: true
  shell: |
    apt-get install build-essentials -y
    apt-get install curl openssl libssl-dev -y
    curl -sL https://deb.nodesource.com/setup_12.x | bash -
    apt-get install nodejs -y

- name: "Install pm2 package"
  become: true
  shell: |
    npm install pm2 -g

- name: "Environment variable read"
  become_user: ubuntu
  shell: |
    grep -c "^export TYPEORM_CONNECTION" /etc/environment || true
  register: test_grep

- name: "Environment variable set"
  become: true
  shell: |
    echo "Env vars for udacity" >> /etc/environment
    echo "export TYPEORM_CONNECTION={{ lookup('env', 'TYPEORM_CONNECTION') }}" >> /etc/environment
    echo "export TYPEORM_ENTITIES=\"./modules/domain/**/*.entity*.{ts,js}"\" >> /etc/environment
    echo "export TYPEORM_HOST={{ lookup('env', 'TYPEORM_HOST') }}" >> /etc/environment
    echo "export TYPEORM_PORT={{ lookup('env', 'TYPEORM_PORT') }}" >> /etc/environment
    echo "export TYPEORM_USERNAME={{ lookup('env', 'TYPEORM_USERNAME') }}" >> /etc/environment
    echo "export TYPEORM_PASSWORD={{ lookup('env', 'TYPEORM_PASSWORD') }}" >> /etc/environment
    echo "export TYPEORM_DATABASE={{ lookup('env', 'TYPEORM_DATABASE') }}" >> /etc/environment
  when: test_grep.stdout == "0"